### PR TITLE
Attempt to make it work in Redmine 3.3

### PR DESCRIPTION
**Pull request by ancorgs**
@darix can you test if that patch fixes the problem. I'm just guessing but...

### CODE REVIEW

**Comment by darix** [comment]
crash is gone. but it doesnt show any public issues anymore.

**Comment by KotUchoniy** [comment]
Redmine 3.4.3 undefined method 'render_sidebar_queries' for module 'IssuesHelper'.
Can you help me?
